"""drop the redundant index on users.id

`ix_users_id` was created by the first migration, which was generated by autogenerate and
committed without adjustment. It indexes the primary key, which both SQLite and
PostgreSQL already index to enforce the constraint — so it costs a write on every insert
and buys nothing.

The reason to remove it now is not the write cost, which is negligible at this size. It is
that the index exists in the schema and not on the model, so `alembic check` reports drift
on a clean database and can never pass. That makes it useless as a CI gate, which is
exactly the check that would have caught this in the first place.

Revision ID: f7a8b9c0d1e2
Revises: e5f6a7b8c9d0
Create Date: 2026-07-27

"""

from collections.abc import Sequence

from alembic import op

revision: str = "f7a8b9c0d1e2"
down_revision: str | Sequence[str] | None = "e5f6a7b8c9d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Drop the redundant primary-key index."""
    op.drop_index(op.f("ix_users_id"), table_name="users")


def downgrade() -> None:
    """Recreate the index, so the revision is reversible even though it is useless."""
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
