"""Word lists backing the deterministic analysis.

Kept as plain frozensets and mappings rather than a data file: they need no packaging,
no filesystem read, and they must work in `local_only` mode where nothing may leave the
machine. This is deliberately a small curated set rather than a full taxonomy — a real
skill ontology (ESCO, O*NET) is a Phase 6 follow-up, and the interfaces here take the
alias map as data so swapping in a larger source needs no code change.
"""

from collections.abc import Mapping, Set
from typing import Final

# Words carrying no signal when matching a job description against a CV.
STOPWORDS: Final[Set[str]] = frozenset(
    {
        "a",
        "about",
        "above",
        "across",
        "after",
        "all",
        "also",
        "an",
        "and",
        "any",
        "are",
        "as",
        "at",
        "be",
        "because",
        "been",
        "being",
        "both",
        "but",
        "by",
        "can",
        "could",
        "did",
        "do",
        "does",
        "doing",
        "down",
        "during",
        "each",
        "either",
        "etc",
        "even",
        "every",
        "for",
        "from",
        "further",
        "had",
        "has",
        "have",
        "having",
        "he",
        "her",
        "here",
        "hers",
        "him",
        "his",
        "how",
        "however",
        "i",
        "if",
        "in",
        "into",
        "is",
        "it",
        "its",
        "itself",
        "just",
        "like",
        "made",
        "make",
        "many",
        "may",
        "me",
        "might",
        "more",
        "most",
        "much",
        "must",
        "my",
        "no",
        "nor",
        "not",
        "now",
        "of",
        "off",
        "on",
        "once",
        "one",
        "only",
        "or",
        "other",
        "our",
        "ours",
        "out",
        "over",
        "own",
        "per",
        "role",
        "s",
        "same",
        "shall",
        "she",
        "should",
        "so",
        "some",
        "such",
        "t",
        "than",
        "that",
        "the",
        "their",
        "them",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "us",
        "very",
        "via",
        "was",
        "we",
        "were",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "why",
        "will",
        "with",
        "within",
        "would",
        "you",
        "your",
        "yours",
        # Job-advert filler that appears in almost every posting.
        "ability",
        "candidate",
        "candidates",
        "company",
        "experience",
        "excellent",
        "good",
        "great",
        "help",
        "join",
        "knowledge",
        "looking",
        "opportunity",
        "position",
        "proven",
        "responsibilities",
        "skills",
        "strong",
        "team",
        "teams",
        "understanding",
        "work",
        "working",
        "years",
        # Requirement markers: they delimit sections, they are not themselves skills.
        "bonus",
        "desirable",
        "essential",
        "familiarity",
        "nice",
        "preferred",
        "require",
        "required",
        "requirement",
        "requirements",
        "qualifications",
    }
)

# Content words about hiring rather than about the job. Unlike STOPWORDS these are
# not function words; without them a posting's own boilerplate scores as a gap.
JOB_POSTING_BOILERPLATE: Final[Set[str]] = frozenset(
    {
        "ability",
        "applicant",
        "apply",
        "background",
        "candidate",
        "career",
        "colleague",
        "company",
        "culture",
        "duties",
        "employee",
        "employer",
        "engineer",
        "excellent",
        "experience",
        "experienced",
        "expertise",
        "familiarity",
        "fully",
        "hiring",
        "join",
        "knowledge",
        "looking",
        "opportunity",
        "position",
        "proficiency",
        "proven",
        "qualifications",
        "requirement",
        "requirements",
        "responsibilities",
        "role",
        "salary",
        "seeking",
        "skills",
        "strong",
        "team",
        "understanding",
        # Scored on its own axis by `analysis.matching`; counting it again as a
        # missing skill double-penalises and reads as "you are missing: remote".
        "hybrid",
        "office",
        "on-site",
        "onsite",
        "remote",
        "week",
        "work",
        "working",
        "year",
        "years",
        # Verbs and nouns every posting contains, never skills. A gap list saying
        # "you are missing: built, building, companies" is not actionable.
        "build",
        "builder",
        "building",
        "built",
        "collaboration",
        # The plural fold only strips a trailing "s"; this one is y -> ies.
        "companies",
        "deliver",
        "delivery",
        "developer",
        "engineering",
        "help",
        "helping",
        "impact",
        "mission",
        "product",
        "project",
        "technology",
        "tool",
        # Three characters once the trailing dot goes, so the length filter passes them.
        "e.g",
        "i.e",
        "etc",
        "best",
        "better",
        "business",
        "businesses",
        "client",
        "commercial",
        "customer",
        "day",
        "global",
        "great",
        "growth",
        "idea",
        "industries",
        "industry",
        "junior",
        "level",
        "need",
        "needed",
        "part",
        "passion",
        "passionate",
        "people",
        "person",
        "place",
        "problem",
        "senior",
        "solution",
        "success",
        "successful",
        "thing",
        "time",
        "top",
        "value",
        "way",
        "world",
    }
)

KNOWN_PHRASES: Final[Set[str]] = frozenset(
    {
        "full stack",
        "machine learning",
        "natural language processing",
        "artificial intelligence",
        "continuous integration",
        "continuous delivery",
        "continuous deployment",
        "test-driven development",
        "infrastructure as code",
        "site reliability engineering",
        "object-oriented programming",
        "domain-driven design",
        "distributed systems",
        "data engineering",
        "data science",
        "amazon web services",
        "google cloud",
        "microsoft azure",
        "rest api",
        "unit testing",
        "integration testing",
        "load testing",
        "code review",
        "version control",
        "message queue",
        "event driven",
        "product management",
        "project management",
        "user experience",
        "user interface",
        "quality assurance",
        "technical leadership",
        "system design",
    }
)

# Distinct spellings that mean the same skill. Both directions are handled by the
# caller: every value is the canonical form.
SKILL_ALIASES: Final[Mapping[str, str]] = {
    "js": "javascript",
    "ecmascript": "javascript",
    "ts": "typescript",
    "py": "python",
    "golang": "go",
    "k8s": "kubernetes",
    "postgres": "postgresql",
    "psql": "postgresql",
    "mongo": "mongodb",
    "node": "node.js",
    "nodejs": "node.js",
    "react.js": "react",
    "reactjs": "react",
    "vue.js": "vue",
    "vuejs": "vue",
    "angularjs": "angular",
    "dotnet": ".net",
    "cicd": "ci/cd",
    "ci-cd": "ci/cd",
    "gcp": "google cloud",
    "aws": "amazon web services",
    "ml": "machine learning",
    "ai": "artificial intelligence",
    "nlp": "natural language processing",
    "iac": "infrastructure as code",
    "tf": "terraform",
    "k6": "load testing",
    "rdbms": "sql",
    "restful": "rest",
    "graphql api": "graphql",
    "oop": "object-oriented programming",
    "tdd": "test-driven development",
    "ddd": "domain-driven design",
    "sre": "site reliability engineering",
    "qa": "quality assurance",
    "ux": "user experience",
    "ui": "user interface",
}

# Marks a dated entry as education. Read from what the entry says, not where it
# sits: a two-column CV interleaves the sidebar into the extracted reading order.
EDUCATION_MARKERS: Final[Set[str]] = frozenset(
    {
        "academy",
        "bachelor",
        "bsc",
        "college",
        "course",
        "courses",
        "degree",
        "diploma",
        "doctorate",
        "escola",
        "faculdade",
        "instituto",
        "institute",
        "licenciatura",
        "master",
        "masters",
        "mba",
        "mestrado",
        "msc",
        "phd",
        "polytechnic",
        "school",
        "universidad",
        "universidade",
        "universitat",
        "universite",
        "university",
    }
)

# Canonical forms, used to check a plural fold produced something real: "APIs" ->
# "api", but never "aws" -> "aw".
KNOWN_TERMS: Final[Set[str]] = frozenset(KNOWN_PHRASES) | frozenset(
    SKILL_ALIASES.values()
)


# Phrases introducing hard requirements in a job description.
REQUIRED_MARKERS: Final[tuple[str, ...]] = (
    "required",
    "requirements",
    "must have",
    "must-have",
    "essential",
    "you will need",
    "what you need",
    "minimum qualifications",
)

# Phrases introducing optional requirements.
PREFERRED_MARKERS: Final[tuple[str, ...]] = (
    "preferred",
    "nice to have",
    "nice-to-have",
    "desirable",
    "bonus",
    "plus",
    "advantageous",
    "would be great",
)

# Verbs that make a CV bullet read as an accomplishment rather than a duty.
ACTION_VERBS: Final[Set[str]] = frozenset(
    {
        "accelerated",
        "achieved",
        "architected",
        "authored",
        "automated",
        "built",
        "consolidated",
        "converted",
        "created",
        "cut",
        "delivered",
        "designed",
        "developed",
        "diagnosed",
        "directed",
        "doubled",
        "drove",
        "eliminated",
        "engineered",
        "established",
        "expanded",
        "founded",
        "generated",
        "grew",
        "implemented",
        "improved",
        "increased",
        "initiated",
        "instituted",
        "integrated",
        "introduced",
        "launched",
        "led",
        "maintained",
        "managed",
        "mentored",
        "migrated",
        "modernised",
        "modernized",
        "negotiated",
        "optimised",
        "optimized",
        "orchestrated",
        "overhauled",
        "pioneered",
        "prototyped",
        "rearchitected",
        "rebuilt",
        "reduced",
        "refactored",
        "released",
        "removed",
        "replaced",
        "resolved",
        "restructured",
        "scaled",
        "shipped",
        "simplified",
        "standardised",
        "standardized",
        "streamlined",
        "supervised",
        "tripled",
        "unified",
        "upgraded",
    }
)

# Section headings an applicant tracking system looks for.
EXPECTED_SECTIONS: Final[Mapping[str, tuple[str, ...]]] = {
    "experience": (
        "experience",
        "employment",
        "work history",
        "professional experience",
        "career history",
    ),
    "education": ("education", "academic", "qualifications"),
    "skills": ("skills", "technical skills", "competencies", "technologies"),
}

# The opening paragraph, under whichever of its half-dozen names the CV used.
#
# Kept out of `EXPECTED_SECTIONS` on purpose: that mapping drives the parseability
# warnings, and an applicant tracking system does not need a summary heading to read a
# CV. Extraction reads it, the checker must not start demanding it.
SUMMARY_HEADINGS: Final[tuple[str, ...]] = (
    "summary",
    "professional summary",
    "career summary",
    "profile",
    "personal profile",
    "professional profile",
    "about me",
    "about",
    "personal statement",
    "objective",
    "career objective",
)

# Headings that end a role's text without holding anything extraction reads.
OTHER_HEADINGS: Final[tuple[str, ...]] = (
    "projects",
    "side projects",
    "personal projects",
    "certifications",
    "certificates",
    "courses",
    "languages",
    "interests",
    "hobbies",
    "awards",
    "achievements",
    "publications",
    "volunteering",
    "volunteer experience",
    "references",
)

# The half of an entry heading that names the institution rather than the qualification.
INSTITUTION_MARKERS: Final[Set[str]] = frozenset(
    {
        "academy",
        "college",
        "escola",
        "faculdade",
        "institute",
        "instituto",
        "polytechnic",
        "school",
        "universidad",
        "universidade",
        "universitat",
        "universite",
        "university",
    }
)

# Words that mark a heading fragment as an employer. Company suffixes, and the nouns
# employers put in their names.
ORGANISATION_MARKERS: Final[Set[str]] = INSTITUTION_MARKERS | frozenset(
    {
        "ag",
        "bank",
        "bv",
        "co",
        "company",
        "corp",
        "corporation",
        "gmbh",
        "group",
        "inc",
        "labs",
        "lda",
        "llc",
        "llp",
        "ltd",
        "plc",
        "s.a",
        "sa",
        "sarl",
        "services",
        "solutions",
        "technologies",
    }
)

# Words that mark a heading fragment as a job title.
ROLE_MARKERS: Final[Set[str]] = frozenset(
    {
        "accountant",
        "administrator",
        "advisor",
        "adviser",
        "analyst",
        "apprentice",
        "architect",
        "assistant",
        "associate",
        "auditor",
        "ceo",
        "cfo",
        "consultant",
        "contractor",
        "controller",
        "coordinator",
        "cto",
        "designer",
        "developer",
        "director",
        "editor",
        "engineer",
        "executive",
        "founder",
        "co-founder",
        "freelance",
        "freelancer",
        "head",
        "intern",
        "internship",
        "lead",
        "lecturer",
        "manager",
        "officer",
        "operator",
        "owner",
        "partner",
        "president",
        "professor",
        "programmer",
        "representative",
        "researcher",
        "scientist",
        "specialist",
        "supervisor",
        "teacher",
        "technician",
        "tester",
        "trainee",
        "traineeship",
        "tutor",
        "vp",
        "writer",
    }
)


# Job-title words that on their own make a role a development one, so a generated CV
# links the applicant's GitHub. "Engineer" is not here: a sales or civil engineer has no
# use for it, and `tailored_cv` decides those from what the posting asks for instead.
DEVELOPMENT_ROLE_MARKERS: Final[Set[str]] = frozenset(
    {
        "back-end",
        "backend",
        "developer",
        "devops",
        "front-end",
        "frontend",
        "full-stack",
        "fullstack",
        "programmer",
        "sre",
        "software",
        "web",
    }
)
